# Generated by Django 4.2 on 2026-03-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_anomalydetection_auditlog_compliancecheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
