# Generated by Django 4.2 on 2026-03-24 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_event_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('analyst', 'Security Analyst'), ('investigator', 'Investigator'), ('admin', 'Administrator'), ('viewer', 'Viewer')], default='analyst', max_length=32)),
                ('department', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=32)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('email_alerts', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=128, unique=True)),
                ('setting_value', models.TextField()),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('boolean', 'Boolean'), ('integer', 'Integer'), ('json', 'JSON')], default='string', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='MITREMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(default=0.5)),
                ('mapped_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitre_mappings', to='core.alert')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitre_mappings', to='core.event')),
                ('ioc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitre_mappings', to='core.ioc')),
                ('mapped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.mitretechnique')),
            ],
            options={
                'verbose_name_plural': 'MITRE Mappings',
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('login_anomaly', 'Login Anomaly'), ('data_exfiltration', 'Data Exfiltration'), ('lateral_movement', 'Lateral Movement'), ('privilege_escalation', 'Privilege Escalation'), ('unusual_activity', 'Unusual Activity'), ('high_risk_command', 'High Risk Command'), ('resource_abuse', 'Resource Abuse')], max_length=64)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('detection_method', models.CharField(max_length=128)),
                ('confidence_score', models.FloatField(default=0.5)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.asset')),
                ('related_alerts', models.ManyToManyField(blank=True, to='core.alert')),
                ('related_events', models.ManyToManyField(blank=True, to='core.event')),
            ],
            options={
                'verbose_name_plural': 'Anomalies',
                'ordering': ['-detected_at'],
            },
        ),
    ]
