# Generated by Django 4.2 on 2026-03-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(max_length=255)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_permanent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('url', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('headers', models.JSONField(default=dict)),
                ('body', models.TextField(blank=True, null=True)),
                ('threat_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('ai_confidence', models.FloatField(help_text='Confidence score from AI (0.0 - 1.0)')),
                ('action_taken', models.CharField(choices=[('BLOCKED', 'Blocked'), ('FLAGGED', 'Flagged'), ('ALLOWED', 'Allowed')], max_length=10)),
                ('details', models.TextField(help_text='AI analysis details')),
            ],
        ),
    ]
